/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("raykasting.kotlin-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("raykasting.app.AppKt")
}
